---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Sorting CEO Incomes

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('ceo_incomes.ok')
```

In this exercise, we'll look at the 2015 compensation of CEOs at the 100 largest companies in California.  These data come from a Los Angeles Times analysis [here](http://spreadsheets.latimes.com/california-ceo-compensation/), and ultimately from [filings](https://www.sec.gov/answers/proxyhtf.htm) mandated by the SEC from all publicly-traded companies.

```{python}
compensation = Table.read_table("compensation.csv")
compensation
```

**Question 1.** Suppose we want to look at the highest-compensated CEOs among these.  Create a version of the table that's sorted in *decreasing* order by the CEO's total compensation.  Call it `compensation_order`.

```{python}
compensation_order = ...
compensation_order
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** Create a version of the table in alphabetical order by last name, but with an extra column called "Rank" for each CEO's rank in terms of total pay.  Call the table `alphabetical_order`.

*Hint:* First add a column of numbers from 1 to 102 to the table *while it's sorted by compensation*, then sort it by name.

```{python}
alphabetical_order = ...
alphabetical_order
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** Create a table named `high_stock_compensation` containing the 5 CEOs with the highest *stock* (not total) compensation.  It should be sorted in *alphabetical order by last name*, and it should have the same columns as `compensation`.

```{python}
high_stock_compensation = ...
high_stock_compensation
```

```{python}
_ = tests.grade('q3')
```

**Question 4.** What's the *smallest* difference in total pay between any 2 of the CEOs?

*Hint:* Try the function `np.diff`.

```{python}
smallest_difference = ...
smallest_difference
```

```{python}
_ = tests.grade('q4')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".incomes_$(date +%m%d_%H%M)_submission.html" incomes.ipynb
```
