---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

<!-- #region {"deletable": true, "editable": true} -->
# Project 3 - Classification
Welcome to the third project of Data 8!  You will build a classifier that guesses whether a song is hip-hop or country, using only the numbers of times words appear in the song's lyrics.  By the end of the project, you should know how to:

1. Build a k-nearest-neighbors classifier.
2. Test a classifier on data.

### Logistics


**Deadline.** This project is due at 11:59pm on Tuesday, 8/8. It's **much** better to be early than late, so start working now.

**Checkpoint.** For full credit, you must also **complete Part 1 of the project (out of 4) and submit them by 11:59pm on Friday 8/4**. You will have some lab time to work on these questions, but we recommend that you start the project before lab and leave time to finish the checkpoint afterward.

**Partners.** You may work with one other partner. It's best to work with someone in your lab. Only one of you is required to submit the project. On [okpy.org](http://okpy.org), the person who submits should also designate their partner so that both of you receive credit.

**Rules.** Don't share your code with anybody but your partner. You are welcome to discuss questions with other students, but don't share the answers. The experience of solving the problems in this project will prepare you for exams (and life). If someone asks you for the answer, resist! Instead, you can demonstrate how you would solve a similar problem.

**Support.** You are not alone! Come to office hours, post on Piazza, and talk to your classmates. If you want to ask about the details of your solution to a problem, make a private Piazza post and the staff will respond. If you're ever feeling overwhelmed or don't know how to make progress, email your TA or tutor for help. You can find contact information for the staff on the [course website](http://data8.org/su17/staff.html).

**Tests.** Passing the tests for a question **does not** mean that you answered the question correctly. Tests usually only check that your table has the correct column labels. However, more tests will be applied to verify the correctness of your submission in order to assign your final score, so be careful and check your work!

**Advice.** Develop your answers incrementally. To perform a complicated table manipulation, break it up into steps, perform each step on a different line, give a new name to each result, and check that each intermediate result is what you expect. You can add any additional names or functions you want to the provided cells. 

To get started, load `datascience`, `numpy`, `plots`, and `ok`.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
import math
from datascience import *

# These lines set up the plotting functionality and formatting.
import matplotlib
matplotlib.use('Agg', warn=False)
# %matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

# These lines load the tests.
from client.api.notebook import Notebook
ok = Notebook('project3.ok')
_ = ok.auth(inline=True)
```

<!-- #region {"deletable": true, "editable": true} -->
# 1. The Dataset

Our dataset is a table of songs, each with a name, an artist, and a genre.  We'll be trying to predict each song's genre.

The only attributes we will use to predict the genre of a song are its lyrics. In particular, we have a list of just under 5,000 words that might occur in a song.  For each song, our dataset tells us the frequency with which each of these words occurs in that song. All words have been converted to lowercase.

Run the cell below to read the `lyrics` table. **It may take up to a minute to load.**
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
lyrics = Table.read_table('lyrics.csv')
lyrics.where("Title", "In Your Eyes").select(0, 1, 2, 3, 4, 5, "like", "love")
```

<!-- #region {"deletable": true, "editable": true} -->
That cell prints a few columns of the row for the country song ["In Your Eyes" by Alison Krauss](http://www.azlyrics.com/lyrics/alisonkrauss/inyoureyes.html).  The song contains 168 words. The word "like" appears twice:  $\frac{2}{168} \approx 0.0119$ of the words in the song. The word "love" appears 10 times: $\frac{10}{168} \approx 0.0595$ of the words. The word "the" doesn't appear at all.

Our dataset doesn't contain all information about a song.  For example, it doesn't describe the order of words in the song, let alone the melody, instruments, or rhythm. Nonetheless, you may find that word frequencies alone are sufficient to build an accurate genre classifier.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
All titles are unique. The `row_for_title` function provides fast access to the one row for each title. 
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
title_index = lyrics.index_by('Title')
def row_for_title(title):
    """Return the row for a title, similar to the following expression (but faster)
    
    lyrics.where('Title', title).row(0)
    """
    return title_index.get(title)[0]
```

<!-- #region {"deletable": true, "editable": true} -->
For example, the fastest way to find the frequency of "love" in the song *In Your Eyes* is to access the `'love'` item from its row.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
row_for_title('In Your Eyes').item('love')
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 1.1
Set `expected_row_sum` to the number that you expect will result from summing all proportions in each row, excluding the first three columns.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Set row_sum to a number that's the (approximate) sum of each row of word proportions.
expected_row_sum = ...
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q1_1")
```

<!-- #region {"deletable": true, "editable": true} -->
Run the cell below to generate a histogram of the actual row sums. It should confirm your answer above, perhaps with a small amount of error.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Run this cell to display a histogram of the sums of proportions in each row.
# This computation might take up to a minute; you can skip it if it's too slow.
Table().with_column('sums', lyrics.drop([0, 1, 2]).apply(sum)).hist(0)
```

<!-- #region {"deletable": true, "editable": true} -->
This dataset was extracted from the [Million Song Dataset](http://labrosa.ee.columbia.edu/millionsong/). Specifically, we are using the complementary datasets from [musiXmatch](http://labrosa.ee.columbia.edu/millionsong/musixmatch) and [Last.fm](http://labrosa.ee.columbia.edu/millionsong/lastfm). 

The counts of common words in the lyrics for all of these songs are provided by the musiXmatch dataset (called a bag-of-words format). We converted the words to lowercase, removed the naughty ones, and converted the counts to frequencies.

The Last.fm dataset contains multiple tags for each song in the Million Song Dataset. Some of the tags are genre-related, such as "pop", "rock", "classic", etc.  To construct the `Genre` column, we first extracted songs with Last.fm tags that included the words "country", or both "hip" and "hop". These songs were then cross-referenced with the musiXmatch dataset, and only songs with musixMatch lyrics were placed into our dataset. 
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
print('Words with frequencies:', lyrics.drop('Title', 'Artist', 'Genre').num_columns)
print('Songs with genres:', lyrics.num_rows)
```

<!-- #region {"deletable": true, "editable": true} -->
## 1.1. Word Stemming
The columns other than Title, Artist, and Genre in the `lyrics` table are all words that appear in some of the songs in our dataset.  Some of those names have been *stemmed*, or abbreviated heuristically, in an attempt to make different [inflected](https://en.wikipedia.org/wiki/Inflection) forms of the same base word into the same string.  For example, the column "manag" is the sum of proportions of the words "manage", "manager", "managed", and "managerial" (and perhaps others) in each song.  

Stemming makes it a little tricky to search for the words you want to use, so we have provided another table that will let you see examples of unstemmed versions of each stemmed word.  Run the code below to load it.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Just run this cell.
vocab_mapping = Table.read_table('mxm_reverse_mapping_safe.csv')
stemmed = np.take(lyrics.labels, np.arange(3, len(lyrics.labels)))
vocab_table = Table().with_column('Stem', stemmed).join('Stem', vocab_mapping)
vocab_table.take(np.arange(1100, 1110))
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 1.1.1
Assign `unchanged` to the **percentage** of words in `vocab_table` that are the same as their stemmed form (such as "devour" above).

*Hint:* Try using `where` and comparing the number of rows in a table of only unchanged vocabulary with the number of rows in `vocab_table`.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
percent_unchanged = ...
print(round(percent_unchanged, 2), 'percent are unchanged')
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q1_1_1")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 1.1.2
Assign `stemmed_message` to the stemmed version of the word "message".
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Set stemmed_message to the stemmed version of "message" (which
# should be a string).  Use vocab_table.
stemmed_message = ...
stemmed_message
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q1_1_2")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 1.1.3
Assign `unstemmed_singl` to the word in `vocab_table` that has "singl" as its stemmed form. (*Note that multiple English words may stem to "singl", but only one example appears in `vocab_table`.*)
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Set unstemmed_singl to the unstemmed version of "singl" (which
# should be a string).
unstemmed_singl = ...
unstemmed_singl
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q1_1_3")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 1.1.4
What word in `vocab_table` was shortened the most by this stemming process? Assign `most_shortened` to the word. It's an example of how heuristic stemming can collapse two unrelated words into the same stem (which is bad, but happens a lot in practice anyway).
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE, for_assignment_type=student}
# In our solution, we found it useful to first make an array
# called shortened containing the number of characters that was
# chopped off of each word in vocab_table, but you don't have
# to do that.
shortened = ...
most_shortened = ...

# This will display your answer and its shortened form.
vocab_table.where('Word', most_shortened)
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q1_1_4")
```

<!-- #region {"deletable": true, "editable": true} -->
## 1.2. Splitting the dataset
We're going to use our `lyrics` dataset for two purposes.

1. First, we want to *train* song genre classifiers.
2. Second, we want to *test* the performance of our classifiers.

Hence, we need two different datasets: *training* and *test*.

The purpose of a classifier is to classify unseen data that is similar to the training data. Therefore, we must ensure that there are no songs that appear in both sets. We do so by splitting the dataset randomly. The dataset has already been permuted randomly, so it's easy to split.  We just take the top for training and the rest for test. 

Run the code below (without changing it) to separate the datasets into two tables.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Here we have defined the proportion of our data
# that we want to designate for training as 11/16ths
# of our total dataset.  5/16ths of the data is
# reserved for testing.

training_proportion = 11/16

num_songs = lyrics.num_rows
num_train = int(num_songs * training_proportion)
num_valid = num_songs - num_train

train_lyrics = lyrics.take(np.arange(num_train))
test_lyrics = lyrics.take(np.arange(num_train, num_songs))

print("Training: ",   train_lyrics.num_rows, ";",
      "Test: ",       test_lyrics.num_rows)
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 1.2.1
Draw a horizontal bar chart with two bars that show the proportion of Country songs in each dataset.  Complete the function `country_proportion` first; it should help you create the bar chart.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE, for_assignment_type=student, manual_problem_id=music_1_2_1}
def country_proportion(table):
    """Return the proportion of songs in a table that have the Country genre."""
    return ...

# The staff solution took 4 lines.  Start by creating a table.
...
```

<!-- #region {"deletable": true, "editable": true} -->
### Checkpoint Reached

You have reached the project checkpoint. Please submit now in order to record your progress. If you go back and revise your answers in the section above after the checkpoint is due, that's ok. Your revised answers will be graded. However, you will only get credit for your checkpoint submission if you have passed the tests provided for every question above.

If you are working with a partner, only one of you needs to submit. For both of you to receive credit, the person who submits must invite the other to be their partner on [okpy.org](http://okpy.org). Please invite your partner now and tell them to accept the invitation **before** the checkpoint deadline!
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
_ = ok.submit()
```

<!-- #region {"deletable": true, "editable": true} -->
# 2. K-Nearest Neighbors - a Guided Example

K-Nearest Neighbors (k-NN) is a classification algorithm.  Given some *attributes* (also called *features*) of an unseen example, it decides whether that example belongs to one or the other of two categories based on its similarity to previously seen examples. Predicting the category of an example is called *labeling*, and the predicted category is also called a *label*.

An attribute (feature) we have about each song is *the proportion of times a particular word appears in the lyrics*, and the labels are two music genres: hip-hop and country.  The algorithm requires many previously seen examples for which both the attributes and labels are known: that's the `train_lyrics` table.

To build understanding, we're going to visualize the algorithm instead of just describing it.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
## 2.1. Classifying a  song

In k-NN, we classify a song by finding the `k` songs in the *training set* that are most similar according to the features we choose. We call those songs with similar features the *nearest neighbors*.  The k-NN algorithm assigns the song to the most common category among its `k` nearest neighbors.

Let's limit ourselves to just 2 features for now, so we can plot each song.  The features we will use are the proportions of the words "like" and "love" in the lyrics.  Taking the song "In Your Eyes" (in the test set), 0.0119 of its words are "like" and 0.0595 are "love". This song appears in the test set, so let's imagine that we don't yet know its genre.

First, we need to make our notion of similarity more precise.  We will say that the *distance* between two songs is the straight-line distance between them when we plot their features in a scatter diagram. This distance is called the Euclidean ("yoo-KLID-ee-un") distance, whose formula is $\sqrt{(x_1 - x_2)^2 - (y_1 - y_2)^2}$.

For example, in the song *Insane in the Brain* (in the training set), 0.0203 of all the words in the song are "like" and 0 are "love".  Its distance from *In Your Eyes* on this 2-word feature set is $\sqrt{(0.0119 - 0.0203)^2 + (0.0595 - 0)^2} \approx 0.06$.  (If we included more or different features, the distance could be different.)

A third song, *Sangria Wine* (in the training set), is 0.0044 "like" and 0.0925 "love".

The function below creates a plot to display the "like" and "love" features of a test song and some training songs. As you can see in the result, *In Your Eyes* is more similar to *Sangria Wine* than to *Insane in the Brain*.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Just run this cell.

def plot_with_two_features(test_song, training_songs, x_feature, y_feature):
    """Plot a test song and training songs using two features."""
    test_row = row_for_title(test_song)
    distances = Table().with_columns(
            x_feature, [test_row.item(x_feature)],
            y_feature, [test_row.item(y_feature)],
            'Color',   ['Unknown'],
            'Title',   [test_song]
        )
    for song in training_songs:
        row = row_for_title(song)
        distances.append([row.item(x_feature), row.item(y_feature), row.item('Genre'), song])
    distances.scatter(x_feature, y_feature, colors='Color', labels='Title', s=200)
    
training = ["Sangria Wine", "Insane In The Brain"]
plot_with_two_features("In Your Eyes", training, "like", "love")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 2.1.1
Compute the distance between the two country songs, *In Your Eyes* and *Sangria Wine*, using the `like` and `love` features only.  Assign it the name `country_distance`.

**Note:** If you have a row object, you can use `item` to get a value from a column by its name.  For example, if `r` is a row, then `r.item("Genre")` is the value in column `"Genre"` in row `r`.

**Note 2:** You can quickly get the row from the `lyrics` table via `row_for_title`. For example, if "Insane In The Brain" is the song title, then `row_for_title("Insane In The Brain")` is the row object for this song.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
in_your_eyes = row_for_title("In Your Eyes")
sangria_wine = row_for_title("Sangria Wine")
country_distance = ...
country_distance
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q2_1_1")
```

<!-- #region {"deletable": true, "editable": true} -->
The `plot_with_two_features` function can show the positions of several training songs. Below, we've added one that's even closer to *In Your Eyes*.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
training = ["Sangria Wine", "Lookin' for Love", "Insane In The Brain"]
plot_with_two_features("In Your Eyes", training, "like", "love")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 2.1.2
Complete the function `distance_two_features` that computes the Euclidean distance between any two songs, using two features. The last two lines call your function to show that *Lookin' for Love* is closer to *In Your Eyes* than *Insane In The Brain*. 
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def distance_two_features(title0, title1, x_feature, y_feature):
    """Compute the distance between two songs with titles title0 and title1
    
    Only the features named x_feature and y_feature are used when computing the distance.
    """
    row0 = ...
    row1 = ...
    ...

for song in make_array("Lookin' for Love", "Insane In The Brain"):
    song_distance = distance_two_features(song, "In Your Eyes", "like", "love")
    print(song, 'distance:\t', song_distance)
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q2_1_2")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 2.1.3
Define the function `distance_from_in_your_eyes` so that it works as described in its documentation.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def distance_from_in_your_eyes(title):
    """The distance between the given song and "In Your Eyes", based on the features "like" and "love".
    
    This function takes a single argument:
      title: A string, the name of a song.
    """
    ...
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q2_1_3")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 2.1.4
Using the features `"like" and "love"`, what are the names and genres of the 7 songs in the **training set** closest to "In Your Eyes"?  To answer this question, make a table named `close_songs` containing those 7 songs with columns `"Title"`, `"Artist"`, `"Genre"`, `"like"`, and `"love"`, as well as a column called `"distance"` that contains the distance from "In Your Eyes".  The table should be **sorted in ascending order by `distance`**.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE, for_assignment_type=student}
# The staff solution took 4 lines.
close_songs = ...
close_songs
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q2_1_4")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 2.1.5
Define the function `most_common` so that it works as described in its documentation below.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def most_common(label, table):
    """The most common element in a column of a table.
    
    This function takes two arguments:
      label: The label of a column, a string.
      table: A table.
     
    It returns the most common value in that column of that table.
    In case of a tie, it returns any one of the most common values
    """
    ...

# Calling most_common on your table of 7 nearest neighbors classifies
# "In Your Eyes" as a country song, 4 votes to 3.
most_common('Genre', close_songs)
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q2_1_5")
```

<!-- #region {"deletable": true, "editable": true} -->
Congratulations are in order -- you've classified your first song!
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
# 3. Features
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Now, we're going to extend our classifier to consider more than two features at a time.

Euclidean distance still makes sense with more than two features. For `n` different features, we compute the difference between corresponding feature values for two songs, square each of the `n`  differences, sum up the resulting numbers, and take the square root of the sum.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.1
Write a function to compute the Euclidean distance between two **arrays** of features of *arbitrary* (but equal) length.  Use it to compute the distance between the first song in the training set and the first song in the test set, *using all of the features*.  (Remember that the title, artist, and genre of the songs are not features.)

**Note:** To convert row objects to arrays, use `np.array`. For example, if `t` was a table, `np.array(t.row(0))` converts row 0 of `t` into an array.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def distance(features1, features2):
    """The Euclidean distance between two arrays of feature values."""
    ...

distance_first_to_first = ...
distance_first_to_first
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_1")
```

<!-- #region {"deletable": true, "editable": true} -->
## 3.1. Creating your own feature set

Unfortunately, using all of the features has some downsides.  One clear downside is *computational* -- computing Euclidean distances just takes a long time when we have lots of features.  You might have noticed that in the last question!

So we're going to select just 20.  We'd like to choose features that are very *discriminative*. That is, features which lead us to correctly classify as much of the test set as possible.  This process of choosing features that will make a classifier work well is sometimes called *feature selection*, or more broadly *feature engineering*.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.1.1
Look through the list of features (the labels of the `lyrics` table after the first three).  Choose 20 common words that you think might let you distinguish between country and hip-hop songs. Make sure to choose words that are frequent enough that every song contains at least one of them. Don't just choose the 20 most frequent, though... you can do much better.

You might want to come back to this question later to improve your list, once you've seen how to evaluate your classifier.  The first time you answer this question, spend some time looking through the features, but not more than 15 minutes.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Set my_20_features to an array of 20 features (strings that are column labels)

my_20_features = ...

train_20 = train_lyrics.select(my_20_features)
test_20 = test_lyrics.select(my_20_features)
```

<!-- #region {"deletable": true, "editable": true} -->
This test makes sure that you have chosen words such that at least one appears in each song. If you can't find words that satisfy this test just through intuition, try writing code to print out the titles of songs that do not contain any words from your list, then look at the words they do contain.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_1_1")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.1.2
In two sentences or less, describe how you selected your features. 
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true, "manual_problem_id": "music_3_1_2"} -->
*Write your answer here, replacing this text.*
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Next, let's classify the first song from our test set using these features.  You can examine the song by running the cells below. Do you think it will be classified correctly?
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
print("Song:")
test_lyrics.take(0).select('Title', 'Artist', 'Genre').show()
print("Features:")
test_20.take(0).show()
```

<!-- #region {"deletable": true, "editable": true} -->
As before, we want to look for the songs in the training set that are most alike our test song.  We will calculate the Euclidean distances from the test song (using the 20 selected features) to all songs in the training set.  You could do this with a `for` loop, but to make it computationally faster, we have provided a function, `fast_distances`, to do this for you.  Read its documentation to make sure you understand what it does.  (You don't need to read the code in its body unless you want to.)
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Just run this cell to define fast_distances.

def fast_distances(test_row, train_rows):
    """An array of the distances between test_row and each row in train_rows.

    Takes 2 arguments:
      test_row: A row of a table containing features of one
        test song (e.g., test_20.row(0)).
      train_rows: A table of features (for example, the whole
        table train_20)."""
    assert train_rows.num_columns < 50, "Make sure you're not using all the features of the lyrics table."
    counts_matrix = np.asmatrix(train_rows.columns).transpose()
    diff = np.tile(np.array(test_row), [counts_matrix.shape[0], 1]) - counts_matrix
    distances = np.squeeze(np.asarray(np.sqrt(np.square(diff).sum(1))))
    return distances
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.1.3
Use the `fast_distances` function provided above to compute the distance from the first song in the test set to all the songs in the training set, **using your set of 20 features**.  Make a new table called `genre_and_distances` with one row for each song in the training set and two columns:
* The `"Genre"` of the training song
* The `"Distance"` from the first song in the test set 

Ensure that `genre_and_distances` is **sorted in increasing order by distance to the first test song**.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE, for_assignment_type=student}
# The staff solution took 4 lines of code.
genre_and_distances = ...
genre_and_distances
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_1_3")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.1.4
Now compute the 5-nearest neighbors classification of the first song in the test set.  That is, decide on its genre by finding the most common genre among its 5 nearest neighbors, according to the distances you've calculated.  Then check whether your classifier chose the right genre.  (Depending on the features you chose, your classifier might not get this song right, and that's okay.)
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Set my_assigned_genre to the most common genre among these.
my_assigned_genre = ...

# Set my_assigned_genre_was_correct to True if my_assigned_genre
# matches the actual genre of the first song in the test set.
my_assigned_genre_was_correct = ...

print("The assigned genre, {}, was{}correct.".format(my_assigned_genre, " " if my_assigned_genre_was_correct else " not "))
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_1_4")
```

<!-- #region {"deletable": true, "editable": true} -->
## 3.2. A classifier function

Now we can write a single function that encapsulates the whole process of classification.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.2.1
Write a function called `classify`.  It should take the following four arguments:
* A row of features for a song to classify (e.g., `test_20.row(0)`).
* A table with a column for each feature (e.g., `train_20`).
* An array of classes that has as many items as the previous table has rows, and in the same order.
* `k`, the number of neighbors to use in classification.

It should return the class a `k`-nearest neighbor classifier picks for the given row of features (the string `'Country'` or the string `'Hip-hop'`).
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def classify(test_row, train_rows, train_classes, k):
    """Return the most common class among k nearest neigbors to test_row."""
    distances = fast_distances(test_row, train_rows)
    genre_and_distances = ...
    ...
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_2_1")
```

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.2.2
Assign `grandpa_genre` to the genre predicted by your classifier for the song "Grandpa Got Runned Over By A John Deere" in the test set, using **9 neighbors** and using your 20 features.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# The staff solution first defined a row object called grandpa_features.
grandpa_features = ...
grandpa_genre = ...
grandpa_genre
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_2_2")
```

<!-- #region {"deletable": true, "editable": true} -->
Finally, when we evaluate our classifier, it will be useful to have a classification function that is specialized to use a fixed training set and a fixed value of `k`.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
#### Question 3.2.3
Create a classification function that takes as its argument a row containing your 20 features and classifies that row using the 5-nearest neighbors algorithm with `train_20` as its training set.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def classify_one_argument(row):
    ...

# When you're done, this should produce 'Hip-hop' or 'Country'.
classify_one_argument(test_20.row(0))
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_2_3")
```

<!-- #region {"deletable": true, "editable": true} -->
## 3.3. Evaluating your classifier
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Now that it's easy to use the classifier, let's see how accurate it is on the whole test set.

**Question 3.3.1.** Use `classify_one_argument` and `apply` to classify every song in the test set.  Name these guesses `test_guesses`.  **Then**, compute the proportion of correct classifications. 
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
test_guesses = ...
proportion_correct = ...
proportion_correct
```

```{python deletable=TRUE, editable=TRUE}
_ = ok.grade("q3_3_1")
```

<!-- #region {"deletable": true, "editable": true} -->
At this point, you've gone through one cycle of classifier design.  Let's summarize the steps:
1. From available data, select test and training sets.
2. Choose an algorithm you're going to use for classification.
3. Identify some features.
4. Define a classifier function using your features and the training set.
5. Evaluate its performance (the proportion of correct classifications) on the test set.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
## 4. Extra Explorations
Now that you know how to evaluate a classifier, it's time to build a better one.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
#### Question 4.1
Find a classifier with better test-set accuracy than `classify_one_argument`.  (Your new function should have the same arguments as `classify_one_argument` and return a classification.  Name it `another_classifier`.)  You can use more or different features, or you can try different values of `k`.  (Of course, you still have to use `train_lyrics` as your training set!)
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# To start you off, here's a list of possibly-useful features:
staff_features = make_array("come", "do", "have", "heart", "make", "never", "now", "wanna", "with", "yo")

train_staff = train_lyrics.select(staff_features)
test_staff = test_lyrics.select(staff_features)

def another_classifier(row):
    return ...
```

<!-- #region {"deletable": true, "editable": true} -->
Briefly describe what you tried to improve your classifier. As long as you put in some effort to improving your classifier and describe what you have done, you will receive full credit for this problem.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true, "manual_problem_id": "music_4_1"} -->
*Write your answer here, replacing this text.*
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Congratulations: you're done with the required portion of the project! Time to submit.
<!-- #endregion -->

```{python}
_ = ok.submit()
```

<!-- #region {"deletable": true, "editable": true} -->
## Ungraded and Optional: A Custom Classifier
Try to create an even better classifier. You're not restricted to using only word proportions as features.  For example, given the data, you could compute various notions of vocabulary size or estimated song length.  If you're feeling very adventurous, you could also try other classification methods, like logistic regression.  If you think you built a classifier that works well, post on Piazza and let us know.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
#####################
# Custom Classifier #
#####################

```

```{python}
_ = ok.submit()
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
print("Running all tests...")
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
print("Finished running all tests.")
```
