---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Computing Remainders

```{python}
# Run this cell, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
exercise03 = load_assignment('exercise03.ok')
```

**Question 1.** Suppose you have an assignment due 17 days from now, and you want to know what day of the week that is.

The number of weeks that pass don't matter, so let's first eliminate them to make the problem easier.  If you divide 17 by 7 (the number of days in a week), the remainder is 3.  That means the assignment is due on the day of the week that's 3 after the current day of the week.

In Python, the operator `%` computes remainders, so `17 % 7` is 3.

Let's arbitrarily label Sunday as day 0 in the week, Monday as day 1, etc.  If today is a Friday, compute the label of the day that's 34 days after today.

```{python}
today = 5
assignment_day = ...
assignment_day
```

```{python}
_ = exercise03.grade('q1')
```

**Question 2.** [Halley's comet](https://en.wikipedia.org/wiki/Halley%27s_Comet) last passed near Earth on February 9, 1986, which was a Sunday.  Astronomers have calculated its next pass near Earth will come 27,563 days after that day.  What day of the week will that be?

Compute your answer as a label (0 through 6) as in question 1.

```{python}
halleys_comet_day = ...
halleys_comet_day
```

```{python}
_ = exercise03.grade('q2')
```

**Question 3.** In an alternate universe, your evil Data8 professor announces at 23:00 (11:00PM) that everyone is assigned a surprise project!  Worse, she says it will be due exactly 55 hours after the announcement.

Use the remainder (`%`) operator to help you compute the hour of the day at which the assignment is due.  (For example, the answer `5` would mean 5:00AM, and `15` would mean 3:00PM.)

```{python}
assignment_hour = (23 + 55) % 24
assignment_hour
```

```{python}
_ = exercise03.grade('q3')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [exercise03.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".exercise03_$(date +%m%d_%H%M)_submission.html" exercise03.ipynb
```
