---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## CFPB Complaints -- A Challenge

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('cfpb_complaints_challenge.ok')
```

This exercise continues another one [FIXME](), with a few more challenging data manipulations.

The Consumer Financial Protection Bureau has collected and published consumer complaints against financial companies since 2011.  The data are available [here](https://dev.socrata.com/foundry/data.consumerfinance.gov/jhzv-w97w) (or at this [direct link](https://data.consumerfinance.gov/resource/jhzv-w97w.csv).  For this exercise, to make your code run faster, we've selected only the data from May 2016.

Run the next cell to load the data.  Each row represents one consumer's complaint.

```{python}
complaints = Table.read_table("complaints.csv")
complaints
```

Some financial institutions specialize in one kind of business, while others offer many products.  We can use the complaints against each company as a rough proxy for the size of its customer base for each product.  

**Question 1.** Find all the companies that have at least 2 products with 100 or more complaints.  For each of those companies, also find the types of products they offer that have at least 100 complaints.  To do this, create a single table called `many_products_companies` with 2 columns: 
* `"company"`: the name of the company, and
* `"products with many complaints"`: an array of names of product types for which the company has at least 100 complaints.

```{python}
# Hint: The staff solution took several lines and defined
# a few extra tables.
many_products_companies = ...
many_products_companies
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** Find all the complaints against those companies.  That is, make a table (called `complaints_against_big_companies`) that's a copy of `complaints`, but with only the rows that are complaints against the companies in `many_products_companies`.

```{python for_assignment_type=student}
complaints_against_big_companies = ...
complaints_against_big_companies
```

```{python}
# Here we're using join just to filter a table.  We join
# the complaints table with the many_products_companies table,
# not to add any columns, but just to take out the rows in
# complaints that don't have a match in many_products_companies.
complaints_against_big_companies = complaints.join('company', many_products_companies.select(0))
complaints_against_big_companies
```

```{python}
_ = tests.grade('q2')
```

The column `"company_response"` tells us how the company acted in response to the complaint, at least according to the CFPB data. For example, a company might address the complaint ("non-monetary relief"), give the customer money to settle the problem ("monetary relief"), or just explain why they won't do anything.

**Question 3.** Are the complaints against these companies more likely to be settled by explanation (rather than by monetary or non-monetary relief) than complaints in general?  Does this imply an association between being a company with several large products and complaint response, a causal relationship between the two, or neither?

```{python for_assignment_type=student}
# Use this cell to work on this problem.
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".cfpb_complaints_challenge_$(date +%m%d_%H%M)_submission.html" cfpb_complaints_challenge.ipynb
```
