---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

DS8 Tutoring Wk1

```{python}
# HIDDEN

from datascience import *
# %matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import numpy as np
```

Welcome to week one!

Let's start by loading the file top250_movies.txt into the table movies.

```{python}
#sol
movies = Table.read_table('top250_movies.txt')
movies
```

Since 250 rows is a lot, we want to look just at 100 rows from this table. 
We'll write code to randomly select 100 different rows from this table.

Start by creating an empty list `rowNums`.


```{python}
#sol
rowNums = []
```

<!-- #region -->
Then generate 100 random integers (from 0 to 249) to put inside `rowNums`, making sure that there are no repeats.

*Hint:* Use for loops. How many times do you need to iterate?
To account for the fact that you might have generated a repeat, use a nested while loop. What do you need to keep track of whether or not there has been a repeat?


*Hint for Method 2:* Use np.random.choice(). Read the doc:http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.random.choice.html
How does it work? What are its inputs and outputs? Remember if you're doing both, you want to reset `rowNums` beforehand so you don't end up with 200 numbers!
<!-- #endregion -->

```{python}
#sol
for i in range(100):
    num = np.random.randint(0,249)
    repeat = num in rowNums
    while (repeat==True):
        num = np.random.randint(0,249)
        repeat = num in rowNums
    
    rowNums.append(num)
    
#sol2
rowNums = np.random.choice(range(250), size=100, replace=False)


    

```

Excellent. Now we have a list of row numbers. We'll use it to sample from the table. Was this a deterministic or probability sample?

If your answer was deterministic, how might we have chosen a probability sample?
If your answer was probability, how might we have chosen a deterministic sample?



#sol
Probability sample, the chance of each row being selected is 1/250.
We could have chosen a deterministic sample by selecting the first 100 rows.


Use `rowNums` to select 100 rows from the table, save it in the variable `shortMov`.

#sampling

```{python}
#sol
shortMov = movies.take(rowNums)
shortMov
```

Now we want to draw some histograms based on the ratings for these movies.
Let's pivot the table by ratings (pivot column) and then year (pivot row), and have the pivot values be the sum of the votes.
Save this pivoted table in `ratingYear`.

```{python}
#sol
ratingYear = shortMov.pivot('Year', 'Rating','Votes',np.sum) 
ratingYear
```

Take a look at this pivoted table. What does it tell us? 
What does it mean for a cell to be 0?


#sol
1. Tells us total number of votes for a specific rating in any given year. 
2. 0 means there were no movies of that rating in that year.


The table `ratingYear` is useful, but it doesn't help us visualize how many movies were in each rating. 
Using `shortMov`, create a table ratings that contains *only* the column of ratings.

```{python}
#sol
ratings = shortMov.select('Rating')
```

Make a histogram with ratings. Have bins that go in increments of .1 starting from the lowest value in ratings all the way to 10.

```{python}
#sol
minVal = np.min(ratings.column(0))
ratings.hist(bins=np.arange(minVal,10.1,.1))
```

Let's see how our histogram compares to the entire 250 movies dataset.
Draw another histogram using the exact same bins as you did above, but this time use the table `fullRatings` that contains a column of all 250 ratings.

```{python}
#sol
fullRatings = movies.select("Rating")
fullRatings.hist(bins=np.arange(minVal,10.1,.1))
```

Do the two histograms look similar? How might we produce a more similar looking histogram without increasing the number of rows selected (100)?


#sol
We could sample with replacement.


Congratulations! You've finished your first tutoring exercise. Be sure to give your tutor feedback on what you liked, didn't like, and would like to cover in the coming weeks!
