---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Basic Array Arithmetic

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('basic_array_arithmetic.ok')
```

**Question 1.** Multiply the numbers 42, 4224, 42422424, and -250 by 157.  For this question, **don't** use arrays.

```{python}
first_product = ...
second_product = ...
third_product = ...
fourth_product = ...
print(first_product, second_product, third_product, fourth_product)
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** Now, do the same calculation, but using an array and only a single multiplication (`*`) operator.  Put the 4 results in an array named `products`.

```{python}
# You may find it useful to first define an array called
# numbers, but you don't have to.
numbers = ...
products = ...
products
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the fixed products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

```{python}
fixed_products = numbers * 1577
fixed_products
```

```{python}
_ = tests.grade('q3')
```

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$.

```{python}
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = ...
celsius_max_temperatures
```

```{python}
_ = tests.grade('q4')
```

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Give your answer in Celsius!**

```{python}
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

# You may find it useful to first define an array named
# celsius_min_temperatures, but you don't have to do that.
celsius_min_temperatures = ...
celsius_temperature_ranges = ...
celsius_temperature_ranges
```

```{python}
_ = tests.grade('q5')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".basic_array_arithmetic_$(date +%m%d_%H%M)_submission.html" basic_array_arithmetic.ipynb
```
