---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Mapping Farmers' Markets

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('farmers_markets.ok')
```

In this exercise, you'll learn how to place markers on a map.  We'll be plotting the locations of farmers' markets around the United States, using a [dataset](https://apps.ams.usda.gov/FarmersMarketsExport/ExcelExport.aspx) collected by the USDA.

The dataset lists the name and location of many farmers' markets.  For some of the markets, it also includes social media links, seasonal hours, and information about the kinds of products sold at the market.  (For those columns, "Y" means "Yes" and "N" means "No".)

It's important to keep in mind that the dataset includes only farmers' markets that have registered with the USDA, and that all the data are self-reported.

**Question 1.** The dataset is in a file called `farmers_markets.csv`.  Load it into a table named `farmers_markets`, and then count:

1. the number of farmers' markets in California, and
2. the proportion of farmers' markets in Wisconsin that sell cheese.

```{python}
farmers_markets = ...
farmers_markets.show(5)

num_markets_in_california = ...
print("There are", num_markets_in_california, "markets in California.")

proportion_markets_selling_cheese_in_wisconsin = ...
print("{:.1%} of markets in Wisconsin sell cheese.".format(proportion_markets_selling_cheese_in_wisconsin))
```

```{python}
_ = tests.grade('q1')
```

The latitude and longitude of each farmer's market are contained in the "y" and "x" columns, respectively.

**Question 2.** Check the documentation for the function `Marker.map`.  The `latitudes` and `longitudes` arguments should be arrays of latitudes and longitudes (numbers).  The first latitude and longitude in those arrays correspond to the first market, and so on.  Use `Marker.map` to draw a map with a marker at the location of every market in the dataset *that's in California*.

(You can make a map of the whole United States if you want, but you may have to wait awhile for your computer to draw it.)

**Note:** Follow the existing skeleton so that the output of the function call is given the name `simple_map`.

```{python}
california_markets = ...
simple_map = ...
simple_map
```

```{python}
_ = tests.grade('q2')
```

This is cool, but not all that useful.  It would be nice, for example, if clicking on the marker for a market showed us the name of the market.

**Question 3.** Check the documentation for `Marker.map` again.  The named argument `labels` is an array of strings, one for each marker.  (So it should have the same length as the `latitudes` and `longitudes` arguments.)  Each string will be displayed as the label of each marker.  Make a map of the markets in California, using the names of the markets as labels.  Call it `labeled_map`.

```{python}
labeled_map = ...
labeled_map
```

```{python}
_ = tests.grade('q3')
```

**Question 4.** The Downtown Berkeley Farmers' Market is located at the intersection of two streets.  (Actually, it takes up more space than that, so the marker is slightly misleading!)  Use `Marker.map` to find those two streets.

```{python for_assignment_type=student}
# Use this cell to write code that helps you find the streets.
```

```{python}
# Fill in the names of the two streets here.
north_south_street = ...
east_west_street = ...
```

```{python}
_ = tests.grade('q4')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".farmers_markets_$(date +%m%d_%H%M)_submission.html" farmers_markets.ipynb
```
