---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Flipping Coins, Continued

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the NumPy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('more_coin_chances.ok')
```

(This exercise continues the exercise called "Coin Chances."  If you're stuck and haven't done the previous part, it might help to start there.)

As you're walking down Bancroft one afternoon, a shadowy figure steps out of Sather Lane and offers you the following game:

> "First, you pay me \$1 to play.  Then, I'll flip 4 fair coins.  ("Fair" means that there's a 50% chance the coin lands heads and a 50% chance it lands tails, and all the coins are independent of each other.)

> "If all of the coins come up heads, then I'll give you \$10."

Let's figure out whether this is a good deal.

First, let's think about the outcomes that can happen. We'll order the coins left to right and denote an outcome by a string like `"HHHH"` (for all heads) or `"THTH"` (for alternating tails and heads).  There are $2^4$, or 16, possible outcomes.  The next cell defines that quantity in Python, for your convenience later.

```{python}
num_coins = 4
num_outcomes_4_coins = 2**num_coins
```

**Question 1.** Are the outcomes equally likely to happen, or are some more likely than others?

*Hint:* Imagine you've seen that the first 3 coins are heads, but you haven't seen how the last coin landed yet.  Are you equally likely to see `"HHHH"` and `"HHHT"`?


*Write your answer here, replacing this text.*


**Question 2.** What is the chance of seeing all heads (`"HHHH"`)?

*Hint:* Remember, the probabilities of all the potential outcomes must add up to 1.  So if there are 5 equally-likely outcomes and only 1 can happen, the probability of each individual outcome must be $\frac{1}{5}$.

```{python}
all_heads_chance_4_coins = ...
all_heads_chance_4_coins
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** On one of the outcomes, `"HHHH"`, you make \$10.  On all the others, you make nothing.  That means \$`10*all_heads_chance_4_coins` is the average amount of money you make when you play the game.  You have to pay \$1 to play the game.  So *on average*, do you make money or lose money?


*Write your answer here, replacing this text.*


**Question 4.** Compute the *probability* of getting all heads in a game with 1 coin, for a game with 2 coins, and so on, up to 50 coins.  Put the results in an array.

*Hint:* Don't write an expression and copy it 50 times! Instead, think about the formula for each entry of the array you want, and use array arithmetic to implement that formula.

```{python}
all_heads_chances = ...
all_heads_chances
```

```{python}
_ = tests.grade('q4')
```

**Question 5.** The shadowy figure offers to change the game by flipping a different number of coins.  (You still pay \$1, and you still win \$10 if all the coins come up heads.)  Calculate the amount of money that you win *on average* for games with 1 coin up to 50 coins.  Subtract the amount you must pay, \$1.

*Hint:* Use your answer to the previous question.

```{python}
average_winnings = ...
average_winnings
```

```{python}
_ = tests.grade('q5')
```

Here's a graph of your answer:

```{python}
Table().with_columns("number of coins", np.arange(1, 50+1), "average winnings ($)", average_winnings).scatter(0)
```

**Question 6.** For which numbers of coins are your average winnings positive?


*Write your answer here, replacing this text.*


**Question 7.** The shadowy figure changes the game again.  This time, you win \$1.25 if the coins don't come up *either* all heads or all tails.  (So, if there are 4 coin flips, you win unless the results are `"HHHH"` or `"TTTT"`.)

Compute the probability that you lose, for games with 1 coin up to 50 coins.  That's just the probability of getting all heads, plus the probability of getting all tails.

```{python}
loss_chances = ...
loss_chances
```

```{python}
_ = tests.grade('q7')
```

**Question 8.** Compute the probability that you *win*, for games with 1 coin up to 50 coins.  The chance that you win is 1 minus the chance that you lose.

*Hint:* Use your answer to the previous problem.

```{python}
win_chances = ...
win_chances
```

```{python}
_ = tests.grade('q8')
```

**Question 9.** Compute your average winnings from this new game, for games with 1 coin up to 50 coins.  Again, that's \$1.25 times the chance that you win, minus the \$1 you pay to play.

```{python}
new_average_winnings = ...
new_average_winnings
```

```{python}
_ = tests.grade('q9')
```

Here's a graph of your answers.

```{python}
Table().with_columns(
        "number of coins", np.arange(1, 50+1),
        "first game average winnings ($)", average_winnings,
        "second game average winnings ($)", new_average_winnings)\
    .scatter(0)
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".more_coin_chances_$(date +%m%d_%H%M)_submission.html" more_coin_chances.ipynb
```
