---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Confusing Names

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('confusing_names.ok')
```

**Question 1.** Some physicists and computer scientists were partying late one night, and they decided to figure out roughly how much beer it would take to cover the whole surface of the Sun 3 meters deep.  They found the following facts:

1. The average density (mass per volume) of the Sun is 1410 $\texttt{kg}/\texttt{m}^3$.
2. The Sun weighs $1.989 \times 10^{30} \texttt{kg}$.
3. The Sun's volume is its weight divided by its density.
4. The Sun is roughly a sphere.
5. The radius of a sphere is $(\texttt{volume} \times \frac{3}{4 \times \pi})^{1/3}$
6. $\pi$ is roughly 3.14159.
7. The surface area of a sphere is $4 \times \pi \times \texttt{radius}^2$.

They wrote code in the next cell to compute the answer.  But the next morning, they couldn't figure out what their code did, because none of the names made sense.  To help clarify their code, replace the names used in the next cell with appropriate names chosen from the following list:

* `required_beer_volume`
* `sun_radius`
* `sun_volume`
* `sun_surface_area`
* `sun_density`
* `pi`
* `sun_weight`

```{python}
a = 1410
b = 1.989 * 10**30
c = 3
d = b / a
e = 3.14159
f = (d * 3/(4*e))**(1/3)
g = 4 * e * f**2
h = c * g
```

```{python}
_ = tests.grade('q1')
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".confusing_names_$(date +%m%d_%H%M)_submission.html" confusing_names.ipynb
```
