---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Mapping Pell Grants

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('pell_grants_map.ok')
```

In a previous exercise (FIXME: link?), we computed the proportion of students in various US states who receive financial aid from the US Federal government in the form of Pell grants. This exercise is designed to be completed after that one; some parts of it won't make sense out of that context. We've put the computational results of that exercise in a file called `pell_proportions`, which is loaded in the cell below.

```{python}
pell_proportions = Table.read_table("pell_proportions.csv")
pell_proportions
```

This is nice, but it's hard to make sense of 59 numbers.  Since US states are physical territories, a map might be helpful.  First, though, let's look at the distribution of Pell grant proportions.


**Question 1.** Make a histogram of the Pell grant proportions.

```{python}
pell_proportions.hist("Pell proportion")
```

**Question 2.** The file `us.json` contains data about the boundaries of each US state.  Load it as a map by calling `Map.read_geojson`.

*Note:* The data come from [NOAA](http://www.nws.noaa.gov/geodata/catalog/national/html/us_state.htm).  We converted them to this format using a tool called `ogr2ogr` (see [here](http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/)) and used [mapshaper](http://www.mapshaper.org) to reduce the resolution to 1% of the original.

```{python}
us_map = Map.read_geojson('us.json')
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** The Map method `color` colors regions in a map according to numbers you specify.  It takes 2 arguments:

1. A table whose first column names each region, and whose second column gives the intensity of the color you want for that region.
2. The named argument `key_on=...`, where the argument itself is a string that tells `color` how you're identifying each region.  In this case, both `pell_proportions` and the map know about each state's abbreviation, so use `key_on="feature.properties.STATE"`.  (This part looks a little bit magical, which is just a flaw in the design of the Maps object.  If you're confused, don't worry too much.)

```{python}
us_map.color(pell_proportions, key_on="feature.properties.STATE")
```

**Question 4.** Describe any pattern you see in the data.  Be sure to mention any parts of the data that *don't* fit the pattern you describe.


*Write your answer here, replacing this text.*


**Question 5.** Describe a different map you'd like to make that would help confirm or invalidate the pattern you described.


*Write your answer here, replacing this text.*

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".pell_grants_map_$(date +%m%d_%H%M)_submission.html" pell_grants_map.ipynb
```
