---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Reading Income Data

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('reading_incomes.ok')
```

In this exercise, we'll look at the 2015 compensation of CEOs at the 100 largest companies in California.  These data come from a Los Angeles Times analysis [here](http://spreadsheets.latimes.com/california-ceo-compensation/), and ultimately from [filings](https://www.sec.gov/answers/proxyhtf.htm) mandated by the SEC from all publicly-traded companies.

We've copied the data in raw form from the LA Times page into a file called `raw_compensation.csv`.  (The page notes that all dollar amounts are in millions of dollars.)  Our task is to turn it into something more usable.


**Question 1.** Load the data into a table called `raw_compensation`.

```{python}
raw_compensation = ...
raw_compensation
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** When we first loaded this dataset, we tried to make a histogram of the CEOs' pay like this:

    raw_compensation.hist("Total Pay")

Explain why that didn't work.  *Hint:* Try it yourself; the error message is informative.


*Write your answer here, replacing this text.*


**Question 3.** Create a table called `pay_in_dollars` with 2 columns: the name of each CEO as it appears in `raw_compensation` (called "Name"), and their total pay in dollars (called "Total Pay (\$)").  **Note:** The data in the `raw_compensation` table are in *millions* of dollars.

*Hint:* If you're stuck, try running the tests; hints will appear as you progress.

```{python}
pay_in_dollars = ...
pay_in_dollars
```

```{python}
_ = tests.grade('q3')
```

**Question 4.** Now create the histogram we wanted to make in question 2.

```{python}
...
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".reading_incomes_$(date +%m%d_%H%M)_submission.html" reading_incomes.ipynb
```
