---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

<!-- #region {"deletable": true, "editable": true} -->
# Week 7 Tutoring
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
# Don't change this cell; just run it. 

import numpy as np
from datascience import *

# %matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
```

<!-- #region {"deletable": true, "editable": true} -->
You flip a coin 10 times and land heads 9 times and tails once. You begin to get suspicious of the coin. Suppose you want to test whether or not that coin is fair. State the null and alternative hypotheses.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Null hypothesis:
The coin is fair. Any deviation from the expected result is due to only random chance.

Alternative Hypothesis:
The coin is not fair. There are some other factors influencing the result other than random chance.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
What test statistic would you use test your hypothesis?
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Number of heads. There are multiple answers that are valid.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
Define a function that simulates flipping a coin ten times. The function should return the value of your test statistic.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
def simulate():
    coin = make_array(0, 1)
    results = make_array()
    for i in np.arange(10):
        results = np.append(results, np.random.choice(coin))
    return np.count_nonzero(results)
simulate()
```

<!-- #region {"deletable": true, "editable": true} -->
Simulate this function 10,000 times and put the results in a histogram.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
stats = make_array()
for i in np.arange(10000):
    stats = np.append(stats, simulate())
Table().with_column('Number of Heads', stats).hist()
```

<!-- #region {"deletable": true, "editable": true} -->
Contruct a 95% confidence interval for the results. What are the upper and lower bounds?
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
lower_bound = percentile(2.5, stats) #SOLUTION
upper_bound = percentile(97.5, stats) #SOLUTION
print('Upper Bound: ' + str(upper_bound))
print('Lower Bound: ' + str(lower_bound))
```

<!-- #region {"deletable": true, "editable": true} -->
Calculate the p value.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}
(np.count_nonzero(stats >= 9) + np.count_nonzero(stats <= 1)) / 10000
```

<!-- #region {"deletable": true, "editable": true} -->
Using a p value cutoff of 1%, what can you say about the coin and the null hypothesis?
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
The p value we calculate is below the p value cutoff, meaning the coin is likely unfair and we can reject the null hypothesis.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
What does the p value represent?
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
The p value represents the chance of finding a test statistic as or more extreme (i.e. in the direction of the alternative hypothesis) as compared to the observed value.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
What does the p value cutoff represent?
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
The p value cutoff represents the arbitrary value at which we decide to reject the null hypothesis.
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
What does the confidence interval represent?
<!-- #endregion -->

<!-- #region {"deletable": true, "editable": true} -->
The confidence interval represents the amount of certainty we have that the test statistic will fall in the corresponding range. In this example, we are 95% certain the test statistic will be between 1 and 9, exclusive.
<!-- #endregion -->

```{python deletable=TRUE, editable=TRUE}

```
