---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Writing Documentation for Functions

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *
```

When you want to figure out how to use a function, typing its name and a question mark in a code cell (and then running the cell) will show you its *documentation*.  It's a good idea to write documentation for the functions you write, too.  This exercise will give you practice with that.

**Question 1.** The function below does something interesting, but it's been left without documentation.  Figure out what it does by calling it.  (We've given three example calls to get you started.)  Then write documentation that would help someone understand what the function does.  At a minimum, you should describe:

* what the function does, in one short sentence;
* the purpose and type of each argument; and
* what the function returns.

You can follow the [NumPy guidelines for documenting functions](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) if you like.

**Note:** To complete this exercise, you need to be able to hear audio output from the device you're using.

```{python for_assignment_type=student}
def mystery_function(arg0, arg1, arg2):
    """
    Documentation goes here.
    """
    v = 10000
    w = v*arg2
    x = np.linspace(arg0, arg1, w)
    y = np.cumsum(x) / v
    z = np.sin(2*np.pi*y)
    from IPython.display import Audio
    return Audio(z, rate=v)
```

```{python}
mystery_function(440, 220, 2)
```

```{python}
mystery_function(220, 440, 2)
```

```{python}
mystery_function(220, 440, 4)
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".writing_documentation_$(date +%m%d_%H%M)_submission.html" writing_documentation.ipynb
```
