---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Pell Grants by State (Discussion Questions)

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('pell_grants_discussion.ok')
```

In a previous exercise (FIXME: link?), we computed the proportion of students in various US states who receive financial aid from the US Federal government in the form of Pell grants.  This exercise is designed to be completed after that one; some parts of it won't make sense out of that context.  We've put the computational results of that exercise in a file called `pell_proportions`, which is loaded in the cell below.

```{python}
pell_proportions = Table.read_table("pell_proportions.csv")
pell_proportions
```

**Question 1.** Sort the states in decreasing order by Pell proportion.

```{python}
pell_proportions_sorted = ...
pell_proportions_sorted
```

```{python}
_ = tests.grade('q1')
```

You might notice that there are 59 rows in this table, while the US has only 50 states!  The abbrevations in the table may not help you unravel this mystery.  (If you're familiar with US state abbreviations, you'll even see some unfamiliar abbreviations.)

Instead, let's get the name of each state.  The table `state_names.csv` has one row per state, with the state's abbrevation and its full name.  (It's based on a table from this [blog post](http://www.fonz.net/blog/archives/2008/04/06/csv-of-states-and-state-abbreviations/) and on this table at [Wikipedia](https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations).)


**Question 2.** Load `state_names.csv` and use it to produce a table called `with_names` with one row per state, with the state's full name, abbrevation, and Pell proportion.

```{python}
state_names = Table.read_table('state_names.csv')
with_names = pell_proportions.join("State (abbreviated)", state_names, "Abbreviation").sort("Pell proportion", descending=True)
with_names
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** Explain the mysterious 9 extra rows.


*Write your answer here, replacing this text.*


**Question 4.** Look at the original data in the tables `sfa` and `hd` from the previous exericse (FIXME: link).  Why do you think schools are assigned IDs, instead of just using their names?  Concretely, describe what would have happened in the previous exercise if the `sfa` table had called Berkeley "UC Berkeley" while the `hd` table had called it "University of California, Berkeley" and we used these names to join the two tables.


*Write your answer here, replacing this text.*


**Question 5.** In the previous exercise, we could have computed the proportion of Pell grant recipients in a different way.  First, compute the proportion of recipients at each school.  Then, after finding each school's state, we group by state.  For each state, we compute the *average* of the proportions of Pell grant recipients at each school.  Would that have produced the same result?  Why or why not?


*Write your answer here, replacing this text.*

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".pell_grants_discussion_$(date +%m%d_%H%M)_submission.html" pell_grants_discussion.ipynb
```
