---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Midterm Review 3
The inhabitants of the planet Zoogon have a simplified version of Earth genetics.  For each genetically-determined numerical trait, each Zoogonian has its own single-column table of numbers for that trait, and its value for that trait is the *average* of the numbers in that table.

For example, a Zoogonian’s bone density is the average value of the numbers in its bone density table.  Here is Zolga's bone density table, and her actual bone density.

```{python}
zolga_bone_density_table.show()
print("Zolga's bone density is", np.mean(zolga_bone_density_table.column("bone density (g/cm^3)")), "grams per cubic centimeter.")
```

Like humans, Zoogonians inherit their genes.  However, Zoogonians are all spawned from a single mother named Mother Zoog.  For each trait, a newborn Zoogonian’s table for that trait is a *simple random sample with replacement* from Mother Zoog’s table for that trait.  Each trait has its own sample size. 

For example, Mother Zoog has a table called `bone_densities`.  For bone density the sample is 5 rows, so every Zoogonian’s bone density table looks like `bone_densities.sample(5, with_replacement=True)`.  Zolga's bone density table was one such sample.


## The third eye stalk
Zoogonians have three eye stalks.  Suppose that the height of the third eye stalk is determined genetically by a random sample of **two** rows from `third_eye_stalk_heights`, Mother Zoog’s table for third-eye-stalk height.  1 row in `third_eye_stalk_heights` has the value 4cm, and the other row has the value 6cm.

**Question 1.**
Which of the following is a probability histogram of the height of a newborn Zoogonian’s third eye stalk?

```{python}
a
```

```{python}
b
```

```{python}
c
```

```{python}
d
```

```{python}
e
```

```{python}
f
```

```{python}
g
```

**Question 2.**
Eliminate the histogram you chose.  Which of the remaining histograms above is the most plausible **empirical** histogram of the heights of **20** newborn Zoogonians’ third eye stalks?


## The omnipresent green orb
Each Zoogonian has a glowing green orb that floats above it at all times.  The brightness of each individual's omnipresent orb (which is measured in lumens) is determined genetically by a random sample of **150** rows from Mother Zoog’s table for orb-brightness, `orb_brightnesses`.  In `orb_brightnesses`, one row has the value 400 lumens, and the other row has the value 500 lumens.

**Question 3.**
Which of the following is the **probability** histogram of the brightness of a newborn Zoogonian’s orb?

```{python}
a
```

```{python}
b
```

```{python}
c
```

```{python}
d
```

```{python}
e
```

```{python}
f
```

```{python}
g
```

```{python}
h
```
