---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Midterm Review 4
# 1. `where_not`
If `t` is a table and `"c"` is the name of one of its columns, then `t.where("c", 3)` produces a smaller table containing rows of `t` where column `c` has value 3.  You decide to make it just as easy to make a table of all the rows where a column is something *other than* a given value.  You write a function called `where_not` to do it.  Its definition starts like this:

```{python}
def where_not(original_table, column_name, value):
    """
    Returns a new table that's like original_table, but without
    any rows where column_name is equal to value.
    """
    return ...
```

Fill in the "`...`".


# 2. What would Python print?
What will be printed when the following cell is run?

```{python}
print("1")

def func2(arg):
    print("2")
    print(arg)

def func3():
    print("3")
    return "return value of func3"

print("4")
func2(func3())
```

# 3. `np.array`, part 1
In baseball, pitchers tend to throw slower fastballs as they get older.  Suppose we are trying to use linear regression to predict fastball speed using age.  We use 6 pitchers with known ages and fastball speeds to test out our model.

In the following code, is the call to `np.array` necessary for the code to work, or is it unnecessary but harmless, or does it cause the code not to work?

```{python}
ages = [21, 22, 23, 24, 25, 30]
regression_slope = -.25
regression_intercept = 101
predicted_speeds = np.array(ages) * regression_slope + regression_intercept
```

# 4. `np.array`, part 2
Assume you've run the code in the previous cell (perhaps without the call to `np.array` if you said it caused it not to work).  Now suppose you set `true_speeds` to an *array* of the true fastball speeds of the 6 pitchers, and then run this code.

In the next cell, is the call to `np.array` necessary for the code to work, or is it unnecessary but harmless, or does it cause the code not to work?

```{python}
residuals = predicted_speeds - true_speeds
sum_squared_residuals = sum(np.array(residuals)**2)
```
