---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Basic Ranges

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('basic_ranges.ok')
```

The Federal Reserve Bank of St. Louis publishes data about jobs in the US.  Below we've loaded data on the proportion of people who are considered able to work but can't find jobs.  (We'll call them "unemployed," though that's an oversimplification.  The source of the data is [here](https://fred.stlouisfed.org/series/NEIPTERM156SFRBRIC).)

```{python}
# Run this cell to load the data.  You don't need to
# read it.
unemployment = Table.read_table("unemployment.csv").column("rate")
unemployment
```

Each number in the array `unemployment` is the unemployment rate at the start of one quarter (a 3-month period) of a year.  The first element is the unemployment rate at the start of the first quarter of 1994.

**Question 1.** Let's label each number with its date.  We'll say that the first quarter of 1994 is 1994.0, the second quarter is 1994.25, the third quarter is 1994.5, and so on.  Create an array called `measurement_dates` with the dates for each number in `unemployment`.

```{python}
measurement_dates = ...
measurement_dates
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** What are the year and quarter of the last measurement?


*Write your answer here, replacing this text.*


**Question 3.** What was the biggest increase in the unemployment rate from one quarter to the next?  Calculate the answer using Python code, *not* by looking at the data yourself.  If you're stuck, run the tests for a hint.

```{python}
biggest_increase = ...
biggest_increase
```

```{python}
_ = tests.grade('q3')
```

**Question 4.** In what year and quarter did that increase happen?  For this question, it's okay to look at the data yourself.  You may still want to run some code, and the cell below is provided for that.


*Write your answer here, replacing this text.*

```{python for_assignment_type=student}
# This cell is provided for exploration.
```

**Question 5.** When was the biggest *decrease* in unemployment, and when did it happen?


*Write your answer here, replacing this text.*

```{python for_assignment_type=student}
# This cell is provided for exploration.
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".basic_ranges_$(date +%m%d_%H%M)_submission.html" basic_ranges.ipynb
```
