---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Breaking Down Expressions


The most important idea in Computer Science is that complicated, useful things can be built by putting together simple parts according to simple rules.  Python code is an important example of this principle.  Once you understand the basic rules, you can code with confidence.  These exercises are designed to give you some practice with those rules.

First, a brief review of subexpressions.

You can take any Python expression that has a value and combine it with other expressions.  For example, you can combine two number-valued expressions by putting a `+` between them to add their values together.  This forms a new, larger expression called a *compound expression*.  The expressions that were combined together are called *subexpressions*.

You can tell if something is a subexpression by checking whether it would make sense to write it in a line by itself.  For example, in the expression `2 * 3`, `2` is a subexpression, but `2 *` isn't, because `2 *` isn't a valid expression.  (Try executing it!)


**Question 1.** List all the subexpressions of the following expression:

    2 + 3
    
Put each subexpression on its own line in the next cell.

*Hint:* There are two of them.

```{python}
...
...
```

**Question 2.** Consider the following expression:

    (1 + 2) * ((3 / 4) ** 5)

Here is a list of almost all the subexpressions of that expression.  One is missing.

1. `1`
2. `2`
3. `3`
4. `4`
5. `5`
6. `(1 + 2)`
7. `((3 / 4) ** 5)`

In the next cell, write the missing expression.

```{python}
...
```

**Question 3.** List all the subexpressions of the following expression:

    (((2**3) / 4) / 5) - 6

Put each subexpression on its own line in the next cell.

```{python}
...
...
...
...
...
...
...
...
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".subexpressions_$(date +%m%d_%H%M)_submission.html" subexpressions.ipynb
```
