---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Counting Calories Burned from Exercise

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('counting_exercise.ok')
```

Suppose you'd like to count how many calories you've burned from exercise.  You do 4 kinds of exercise: yoga, walking, sprinting, and volleyball.  Every day in January, you record how many minutes of each kind of exercise you did that day.  Those data are in a table called `exercise.csv`.

```{python}
exercise = Table.read_table('exercise.csv')
exercise
```

Different forms of exercise burn calories at different rates; for example, sprinting is more vigorous than walking.  Using an online tool (for example, [this one](https://www.healthstatus.com/perl/calculator.cgi)), you've estimated how many calories you typically burn per minute of each kind of exercise.  Those estimates are provided below.

```{python}
calories_per_minute = Table.read_table('calories_per_minute.csv')
cpm_yoga = calories_per_minute.where('Exercise', 'yoga').column("Calories per minute").item(0)
cpm_walking = calories_per_minute.where('Exercise', 'walking').column("Calories per minute").item(0)
cpm_sprinting = calories_per_minute.where('Exercise', 'sprinting').column("Calories per minute").item(0)
cpm_volleyball = calories_per_minute.where('Exercise', 'volleyball').column("Calories per minute").item(0)
calories_per_minute
```

To compute the calories you've burned on a particular day, you multiply the time spent on each kind of exercise by the calories burned per minute by that exercise, then add up those 4 numbers.

**Question 1.** Write a function called `compute_calories`.  It should take 4 arguments, the amounts of time (in minutes) spent on yoga, walking, sprinting, and volleyball, respectively.  It should return the total number of calories burned.

```{python for_assignment_type=student}
...
```

```{python}
def compute_calories(yoga_time, walking_time, sprinting_time, volleyball_time):
    return yoga_time*cpm_yoga\
         + walking_time*cpm_walking\
         + sprinting_time*cpm_sprinting\
         + volleyball_time*cpm_volleyball
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** Make a table called `exercise_with_totals` that's a copy of `exercise`, but with an additional column called "Total calories burned exercising".  That column should contain the total number of calories burned from exercise on each day.  Compute that column using `apply` and your `compute_calories` function.

*Hint:* If the second argument to `apply` is an array of column names, your function will be called with several arguments, one for each of those columns.

```{python}
exercise_with_totals = ...
exercise_with_totals
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** How many calories were burned from exercise in the 2nd week of January (that is, on days 8 through 14, inclusive)?  Call that number `calories_burned`.  Compute the answer with code, not by looking at the data.

```{python}
calories_burned = ...
calories_burned
```

```{python}
_ = tests.grade('q3')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".counting_exercise_$(date +%m%d_%H%M)_submission.html" counting_exercise.ipynb
```
