---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Homework 2: Arrays and Tables


**Reading**: Textbook chapters [4](http://www.inferentialthinking.com/chapters/04/data-types.html) and [5](http://www.inferentialthinking.com/chapters/05/tables.html).


Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to load the provided tests. Each time you start your server, you will need to execute this cell again to load the tests.

Homework 2 is due Tuesday, 6/27 at 11:59pm. Start early so that you can come to office hours if you're stuck. Check the website for the office hours schedule.

```{python}
# Don't change this cell; just run it. 

import numpy as np
from datascience import *

from client.api.notebook import Notebook
ok = Notebook('hw02.ok')
_ = ok.auth(inline=True)
```

**Important**: The `ok` tests don't always tell you that your answer is correct. More often, they help catch careless mistakes. It's up to you to ensure that your answer is correct. If you're not sure, ask someone (not for the answer, but for some guidance about your approach).


Once you're finished, select "Save and Checkpoint" in the File menu and then execute the `submit` cell below. Check your Okpy account to see if your backup has saved successfully. If you submit more than once before the deadline, we will only grade your final submission.

```{python}
_ = ok.submit()
```

## 1. Studying the Survivors



The Reverend Henry Whitehead was skeptical of John Snow’s conclusion about the Broad Street pump. After the Broad Street cholera epidemic ended, Whitehead set about trying to prove Snow wrong.  (The history of the event is detailed [here](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1034367/pdf/medhist00183-0026.pdf).)

He realized that Snow had focused his analysis almost entirely on those who had died. Whitehead, therefore, investigated the drinking habits of people in the Broad Street area who had not died in the outbreak.

What is the main reason it was important to study this group?

1) If Whitehead had found that many people had drunk water from the Broad Street pump and not caught cholera, that would have been evidence against Snow's hypothesis.

2) Survivors could provide additional information about what else could have caused the cholera, potentially unearthing another cause.

3) Through considering the survivors, Whitehead could have identified a cure for cholera.

```{python}
# Set survivor_answer to 1, 2, or 3
survivor_answer = ...
```

```{python}
_ = ok.grade('q1_1')
```

**Note:** Whitehead ended up finding further proof that the Broad Street pump played the central role in spreading the disease to the people who lived near it. Eventually, he became one of Snow’s greatest defenders.


## 2. Creating Arrays



**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `math` module.

```{python}
# Our solution involved one extra line of code before creating
# weird_numbers.
...
weird_numbers = ...
weird_numbers
```

```{python}
_ = ok.grade('q2_1')
```

**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves".

```{python}
book_title_words = ...
book_title_words
```

```{python}
_ = ok.grade('q2_2')
```

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(book_title_words)` .

```{python}
with_commas = ...
without_commas = ...

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)
```

```{python}
_ = ok.grade('q2_3')
```

## 3. Indexing Arrays



These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.  


**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

```{python}
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = ...
third_element
```

```{python}
_ = ok.grade('q3_1')
```

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information in the cell (the strings that are currently "???") to complete the table.

```{python}
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", "???", "???", "fifth"),
    "Index",                     make_array("???", "1", "2", "???", "4"),
    "Element",                   some_numbers)
elements_of_some_numbers
```

```{python}
_ = ok.grade('q3_2')
```

**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 142 elements.  What is the index of its last element?

```{python}
index_of_last_element = ...
```

```{python}
_ = ok.grade('q3_3')
```

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`.

```{python}
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = ...
most_recent_birth_year
```

```{python}
_ = ok.grade('q3_4')
```

## 4. Basic Array Arithmetic



**Question 1.** Multiply the numbers 42, 4224, 42422424, and -250 by 157.  For this question, **don't** use arrays.

```{python}
first_product = ...
second_product = ...
third_product = ...
fourth_product = ...
print(first_product, second_product, third_product, fourth_product)
```

```{python}
_ = ok.grade('q4_1')
```

**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

```{python}
numbers = ...
products = ...
products
```

```{python}
_ = ok.grade('q4_2')
```

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the fixed products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

```{python}
fixed_products = ...
fixed_products
```

```{python}
_ = ok.grade('q4_3')
```

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Round each result to the nearest integer using the `np.round` function.

```{python}
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = ...
celsius_max_temperatures
```

```{python}
_ = ok.grade('q4_4')
```

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Give your answer in Celsius!**

```{python}
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_temperature_ranges = ...
celsius_temperature_ranges
```

```{python}
_ = ok.grade('q4_5')
```

## 5. Old Faithful



Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.


**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

```{python}
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = ...
longest = ...
average = ...

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")
```

```{python}
_ = ok.grade('q5_1')
```

**Question 2.** Assign `biggest_decrease` to the biggest descrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. *Hint*: You'll need an array arithmetic function [mentioned in the textbook](https://www.inferentialthinking.com/chapters/04/4/arrays.html#Functions-on-Arrays).

```{python}
biggest_decrease = ...
biggest_decrease
```

```{python}
_ = ok.grade('q5_2')
```

**Question 3.** If you expected Old Faithful to erupt every hour, you would expect to wait a total of `60 * k` minutes to see `k` eruptions. Set `difference_from_expected` to an array with 272 elements, where the element at index `i` is the absolute difference between the expected and actual total amount of waiting time to see the first `i+1` eruptions.  *Hint*: You'll need to compare a cumulative sum to a range.

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)` should be $|207 - 180| = 27$.

```{python}
difference_from_expected = ...
difference_from_expected
```

```{python}
_ = ok.grade('q5_3')
```

**Question 4.** If instead you guess that each waiting time will be the same as the previous waiting time, how many minutes would your guess differ from the actual time, averaging over every wait time except the first one.

For example, since the first three waiting times are 79, 54, and 74, the average difference between your guess and the actual time for just the second and third eruption would be $\frac{|79-54|+ |54-74|}{2} = 22.5$.

```{python}
average_error = ...
average_error
```

```{python}
_ = ok.grade('q5_4')
```

## 6. Tables



**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: "fruit name" and "count".  Give it the name `fruits`.

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

```{python}
# Our solution uses 1 statement split over 3 lines.
fruits = ...
        ...
        ...
fruits
```

```{python}
_ = ok.grade('q6_1')
```

**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit.  Load it as a table named `inventory`.

```{python}
inventory = ...
inventory
```

```{python}
_ = ok.grade('q6_2')
```

**Question 3.** Does each box at the fruit stand contain a different fruit?

```{python}
# Set all_different to "Yes" if each box contains a different fruit or to "No" if multiple boxes contain the same fruit
all_different = ...
all_different
```

```{python}
_ = ok.grade('q6_3')
```

**Question 4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`.

```{python}
sales = ...
sales
```

```{python}
_ = ok.grade('q6_4')
```

**Question 5.** How many fruits did the store sell in total on that day?

```{python}
total_fruits_sold = ...
total_fruits_sold
```

```{python}
_ = ok.grade('q6_5')
```

**Question 6.** What was the store's total revenue (the total price of all fruits sold) on that day?

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

```{python}
total_revenue = ...
total_revenue
```

```{python}
_ = ok.grade('q6_6')
```

**Question 7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's count, so that the "count" is the amount of fruit remaining after Saturday.

```{python}
remaining_inventory = ...
    ...
    ...
    ...
remaining_inventory
```

```{python}
_ = ok.grade('q6_7')
```
