---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Consumer Financial Protection Bureau Complaints

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('cfpb_complaints.ok')
```

The Consumer Financial Protection Bureau has collected and published consumer complaints against financial companies since 2011.  The data are available [here](https://dev.socrata.com/foundry/data.consumerfinance.gov/jhzv-w97w) (or at this [direct link](https://data.consumerfinance.gov/resource/jhzv-w97w.csv).  For this exercise, to make your code run faster, we've selected only the data from May 2016.

Run the next cell to load the data.  Each row represents one consumer's complaint.

```{python}
# Just run this cell.
complaints = Table.read_table("complaints.csv")
complaints
```

**Question 1.** What products are included in the data?  Make a bar chart showing how many complaints were made about each product category.

```{python}
...
```

**Question 2.** How many complaints were made about each company *and product category*?  To answer this question, make a table with 3 columns: the company's name, the product category, and the number of complaints.  Sort it in descending order by number of complaints.

```{python}
by_company_and_product = ...
by_company_and_product
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** There are 3 major credit rating agencies that issue credit reports for people in the US.  Based on the data, what do you think they are?


*Write your answer here, replacing this text.*


**Question 4.** From the data, do you conclude that credit rating agencies have worse customer service than other kinds of financial institutions in the US?  Explain briefly.


*Write your answer here, replacing this text.*


The column `"company_response"` tells us how the company acted in response to the complaint, at least according to the CFPB data.  For example, a company might address the complaint ("non-monetary relief"), give the customer money to settle the problem ("monetary relief"), or just explain why they won't do anything.


**Question 5.** Do you notice a difference in the responses of the three credit rating agencies to complaints about credit reporting?  Write code to help answer this question, then give a written answer.

*Hint:* Use `groups`.

```{python for_assignment_type=student}
# Use this cell to work on this problem.
```

*Write your answer here, replacing this text.*

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".cfpb_complaints_$(date +%m%d_%H%M)_submission.html" cfpb_complaints.ipynb
```
