---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Fixing Misspellings

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.
import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('basic_apply.ok')
```

You're editing a collection of your essays for publication, and you discover that you've been misspelling the word "misspell" as "mispel" your whole life.  You decide to use Python to correct this embarrassing mistake.

**Question 1.** Write a function called `correct_mispel`.  It should take a single string as its argument, and return the same string, but with all instances of "mispel" replaced with "misspell".

*Hint:* Use the string method `.replace`.  It takes two arguments: the piece of text you want to find, and the piece of text you want to replace it with.

```{python for_assignment_type=student}
# Write a function called correct_mispel in this cell.
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** Now you need to load your data into Python.  The file `essay_filenames.csv` is a table that contains the *filenames* of your essays.  Each filename is a string that's the name of an essay.  Load it into a table called `essay_filenames`.

```{python}
essay_filenames = ...
essay_filenames
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** Below, we've provided a function that takes as its argument the *filename* of an essay and returns the text in that file (as one long string).  Using `apply`, create a table called `essays` with two columns:

1. "Name": The filename of the essay
2. "Text": The whole text of the essay

(The essays are actually books from [Project Gutenberg](gutenberg.org), modified to misspell "misspell".  Attributions and copyright information are contained in the text of each essay.)

```{python}
def load_essay(filename):
    """Loads the text in the given file, returning it as one long string."""
    with open(filename, 'r') as essay_file:
        return essay_file.read()

essays = ...
essays
```

```{python}
_ = tests.grade('q3')
```

**Question 4.** Using `apply` and the function you wrote earlier, create a table called `corrected_essays` with two columns:

1. "Name": The filename of the essay
2. "Corrected text": The whole text of the essay, with "mispel" corrected as "misspell".

```{python}
corrected_essays = ...
corrected_essays
```

```{python}
_ = tests.grade('q4')
```

Did this do anything?  Were there even misspellings in the original essay?  Let's find out.

**Question 5.** The string method `splitlines` produces an array of the lines of the string.  Use it to make a table called `news_writing_lines` with a column called "Line" containing the lines from the text called "News Writing".

```{python}
news_writing = ...
news_writing_lines = ...
news_writing_lines
```

```{python}
_ = tests.grade('q5')
```

**Question 6.** Use the table method `where` and the predicate `are.containing` to find all the lines in `news_writing_lines` that include the word "mispel".  Make a table of those lines called `misspelled_lines`.

*Note:* You should also find versions of "mispel" like "mispeled" or "mispeling", and your code probably corrected those, too.  That's okay.

```{python}
misspelled_lines = ...
misspelled_lines
```

```{python for_assignment_type=student}
_ = tests.grade('q6')
```

**Question 7.** In the cell below, repeat the work you did in questions 5 and 6, but for the corrected version of "News Writing" you produced in `corrected_essays`.  Did your correction fix the misspellings?

```{python for_assignment_type=student}
# Use this cell to check whether your code fixed the misspellings.
```

*Write your answer here, replacing this text.*

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".basic_apply_$(date +%m%d_%H%M)_submission.html" basic_apply.ipynb
```
