---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Differences between Universities

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('universities.ok')
```

**Question 1.** Suppose you're choosing a university to attend, and you'd like to *quantify* how *dissimilar* any two universities are.  You rate each university you're considering on 3 traits, using a 0 to 10 scale for each trait:

1. Cost to attend (0 for the cheapest)
2. Graduation rate
3. How cool its mascot is

You decide that the dissimilarity between two universities is:

* the maximum of
* the absolute values of
* the 3 differences in their trait values.

Using this method, compute the dissimilarity between Stanford (whose traits are 8, 9, and 0, respectively) and Berkeley (whose traits are 7, 9, and 10, respectively).  Call your answer `dissimilarity`.  Use a single line of code to compute the answer.  Use Python to do all the steps, including arithmetic (like subtracting 8 from 7).

```{python}
dissimilarity = ...
dissimilarity
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** Identify all the subexpressions in your answer to the previous question.  Write each on its own line.

*Hint:* If your answer to the previous question was as straightforward as possible, there should be 12 subexpressions, not including the whole expression itself.

```{python}
...
...
...
...
...
...
...
...
...
...
...
...
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".universities_$(date +%m%d_%H%M)_submission.html" universities.ipynb
```
