---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

Notebook exercises based off Prof Gonzalez's DS100 lecture

```{python}
import numpy as np
from datascience import *

# %matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
```

# Data 8 Tutoring Week 3

Topics to go over:

- Histograms (Question 2.1 - 2.5)
    - Horizontal and vertical axes 
    - Counts in bins, Unequal bins
    - General principle/ Calculations
    - Bar chart vs. Histograms

- Functions 
    - def statements (Question 3.1)
    - apply (Question 3.2)
    - Functions as values 

- Group
    - Classify by one variable (Question 3.3, 4.1, 4.2)
    - Cross classify by 2 variables (Question 4.3)
    - Pivot tables (Question 3.4, 3.5)
    - Finding distributions with pivoted tables


# Social Security Association

Every year, the SSA records all of the baby names who have social security numbers. The "Count" column describes how many people of each name were born in that year. 
For example, there were 295 female Marys in California in the year 1910. (The first row in the baby_names table)

```{python}
# Just run!
column_labels = make_array('State', 'Gender', 'Year', 'Name', 'Count')
baby_names = Table().read_table("CA.csv", names = column_labels)
baby_names
```

## Question 1: What's the data?
How much data do we have?
How many years does this span?
How many people did they record?

```{python}
num_entries = ...
earliest_year = ...
lastest_year = ...
total_people = ...

# Don't change anything below
print("Number of entries: " + str(num_entries))
print("Time period of data: " + str(earliest_year) + " to " + str(lastest_year))
print("People recorded: " + str(total_people))
```

## Question 2.1: Histograms
First, discuss what each entry (row) of the table represents. What do you think a histogram's bins are?

Next, make a histogram using the numerical data in the column, Years. Use the year_bins as the bins for your histogram. What do you think the histogram is saying? Discuss the x and y axis.

```{python}
year_bins = np.arange(1910, 2020, 10)

# Make your histogram here
```

*** Write your response here ***


## Question 2.2
Why do you see a steady increase from 1920 to 2010?


*** Write your response here ***



## Question 2.3
Calculate the area in the 1980-1990 bin to get the proportion of names recorded from 1980-1990, and name it area_80_90. If we multiply area_80_90 by the total number of entries, we should get the number of names in that time period. Name this variable num_names_80_90.

Hint: When we mean calculate the area from a histogram, look at and use the actual displayed histogram.

Hint: Remember that the y axis is PERCENT per unit, not PROPORTION per unit!
Check your answer by comparing with the number of names 

```{python}
area_80_90 = ...
num_names_80_90 = ...
num_names_80_90
```

## Questions 2.4

Check your answer by comparing num_names_80_90 with the actual number of names recorded from 1980 to 1990. To get the actual number, use the baby_names table.

The number should be close to each other (maybe 5000 off) because the area calculation is not super accurate.

```{python}
# may take ~10 seconds to load
actual = ...
actual
```

Your calculation shows that the area of a bin is indeed the proportion of entries in that bin! Remember, the area of a histogram is extremely important!


## Question 2.5 

Create a visualization that shows the frequency of values in the column, Counts. Use bins that range from 0 to 1000, with the width 50 for each bin. What is interesting about the visualization? What noticable trend do you see? 

```{python}
# Make your visualization here 
```

***Write your answer here***



## Question 3.1: Let's define a function

Usually, we can guess the gender of a person with his or her name. One simple way you might guess is that the names of females more often start with vowels, instead of consonants. Let's find out if that's really true!

Define a function, named ends_with_vowel, that takes in a name argument and returns the first letter as a capital letter. For example first_letter("blake") will return "B".

Hint: str.upper() capitalizes the entire string 

Hint 2: str[index] will return the letter at a given index (just like tbl.item(index) )

```{python}
# Write your function here.

first_letter("blake") #should return 'B'
```

## Question 3.2
Add a column to baby_names, named First Letter, that extracts the first letter from the Name column. Set the new table to baby_names.

```{python}
baby_names = ...
baby_names
```

## Question 3.3
For each letter, how many people were born with that letter as their first letter of their name?
Create a table that has a row for every first letter and the number of people whose names start with that letter. The table should be two columns. (Don't assign the table a name)

Sort it in descending order.

```{python}
# Make the table here
```

## Question 3.4
Although this tells us how many people were born with a certain first letter, this doesn't show us any relationship with a person's gender.

Make a pivot table, called pivot_by_first_letter, where the rows labels are the first letter of a name and the column labels are the two genders. We want to see the total babies who were female and male for each given name.

```{python}
pivot_by_first = ...
pivot_by_first
```

The pivot table is somewhat hard to read because the number are so big. Let's fix that by turning the numbers into proportions of males and females for each letter. You don't need to fully understand the next code cell, but make sure you understand the new pivot table before moving on.

```{python}
# Just run this cell
totals = pivot_by_first.column('F') + pivot_by_first.column('M')
pivot_w_proportions = Table().with_columns('First Letter', pivot_by_first.column('First Letter'),
                                           'F', pivot_by_first.column('F')/totals,
                                           'M', pivot_by_first.column('M')/totals)
pivot_w_proportions.show()
```

## Question 3.5
We said earlier that perhaps if a name started with a vowel, the person is a female. For which vowels is this true? For which vowels is this false? Is this method a good way to guess the gender?



*** Write your response here ***


## Question 4.1: Grouping!
Find the 5 most popular baby names in the US throughout time. Do this by making a table that shows the 5 Names and Counts of all the people who had that name. Name this table top5.

Note: There are a lot of functions that go into this! This is a hard question.

```{python}
top5 = ...
top5
```

## Question 4.2
Let's see if these names correspond with the 5 most popular first letters. Find the 5 most popular first letters in the US throughout time. You should end up with a table that shows the 5 First Letters and Counts of all the people who had that first letter. Name this top5_letter. 

```{python}
top5_letter = ...      
top5_letter
```

## Question 4.3
Some names are gender neutral, which means boys and girls have this name. Look at the counts of people by cross-classifying by name AND gender. Name this table by_name_gender. 

```{python}
by_name_gender = ...
by_name_gender
```

Some common names are thought of as gender neutral. Use the next code cell to look at some commonly known gender neutral names like Leslie, Cameron, Sam, Jordan, Taylor. You can also input whatever name you would like to see!

Are you surprised by the number of females or males with these names? Maybe they aren't as gender neutral as you thought.

```{python}
by_name_gender.where('Name', are.equal_to(##Insert a name here##)) # enter a string!
```

```{python}

```
