---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

## Indexing Arrays

```{python}
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('indexing_arrays.ok')
```

These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.  Unfortunately, this small detail can cause a disproportionate amount of confusion.  So it's useful to practice indexing arrays, even if it's not a particularly important concept.


**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

```{python}
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = ...
third_element
```

```{python}
_ = tests.grade('q1')
```

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information in the cell (the strings that are currently "???") to complete the table.

(Don't worry about the "Table" stuff -- all you need to do is run the cell and replace the `"???"` expressions with the right strings.  You'll learn about tables soon.)

```{python}
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", "???", "???", "fifth"),
    "Index",                     make_array("???", "1", "2", "???", "4"),
    "Element",                   some_numbers)
elements_of_some_numbers
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 142 elements.  What is the index of its last element?

```{python}
index_of_last_element = ...
```

```{python}
_ = tests.grade('q3')
```

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  Find the last element in that array.  (It's the birth year of John F. Kennedy, as of 2016 the most recently-born deceased US President.)  Do this **without** examining the data manually.  (So your answer shouldn't include anything that could change if we changed the dataset.)

```{python}
# Don't worry about how this line works -- you'll learn about
# tables soon.
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = ...
most_recent_birth_year
```

```{python}
_ = tests.grade('q4')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

```{python}
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

# !TZ=America/Los_Angeles ipython nbconvert --output=".indexing_arrays_$(date +%m%d_%H%M)_submission.html" indexing_arrays.ipynb
```
